#!/bin/bash

# Компиляция исходников

javac -sourcepath ./src -classpath ./lib/logback-core-1.2.3.jar:./lib/logback-classic-1.2.3.jar:./lib/slf4j-api-1.7.25.jar -d bin ./src/edu/csf/oop/java/chess/Game/Main.java

# Создание jar архива
# Запускается командой java -jar путь к архиву

jar --create --file Chess_att1.jar --manifest manifest.mf -C ./bin/ .